# Generated by Django 5.0 on 2023-12-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=200)),
                ('manager_email', models.EmailField(max_length=254, unique=True)),
                ('manager_hpass', models.CharField(max_length=200)),
            ],
        ),
    ]
